name: PDF to HTML Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pdf2htmlex
        run: |
          sudo apt-get update
          sudo apt-get install -y pdf2htmlex

      - name: Remove existing HTML files
        run: |
          rm -f docs/*

      - name: Convert PDF to HTML
        run: |
          echo "</ul></body></html>" >> docs/index.html
          mkdir -p docs
          echo "<html><body><ul>" > docs/index.html
          find . -name "*.pdf" -print0 | while IFS= read -r -d '' file; do
            filename=$(basename "$file" .pdf)
            htmlname="docs/$filename.html"
            pdf2htmlEX --embed cfijo --dest-dir "$htmlname" "$file"
            echo "<li><a href='$filename.html'>$filename</a></li>" >> docs/index.html
          done
          echo "</ul></body></html>" >> docs/index.html
          find docs -name "*-html.html" -exec bash -c 'mv "$0" "${0//-html/}"' {} \;

      - name: Generate sitemap.xml
        run: |
          cd docs
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > sitemap.xml
          echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" >> sitemap.xml
          for file in *.html; do
            filename=$(basename "$file" .html)
            echo "  <url>" >> sitemap.xml
            echo "    <loc>https://vincentvandijk96.github.io/WOO/$filename.html</loc>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done
          echo "</urlset>" >> sitemap.xml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -u
          git add docs/*
          git status
          git commit -m "Convert PDF to HTML and generate sitemap"
          git push
